files:
  - source: /src/**/*.resx
    ignore:
      - /**/DevToys.Tools/**/*.*
      - /**/*.%locale%%file_extension%
      - /**/DevToys.UnitTests/**/*.*
    translation: '%original_path%/%file_name%.%locale%%file_extension%'
