files:
  - source: /src/**/*.resx
    ignore:
      - /**/DevToys.Tools/**/*.*
      - /**/*.%locale%%file_extension%
      - /**/DevToys.UnitTests/**/*.*
    translation: /src/**/%file_name%.%locale%.%file_extension%
